# Generated by Django 3.1.4 on 2020-12-16 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autore',
            old_name='conome',
            new_name='cognome',
        ),
    ]
